### ISSUE TITLE
Typeerror when viewing a log

### ISSUE THREAD

**Issue by aleth** [arlolra/ctypes-otr#52]
Timestamp: 25/06/2015 16:14:15
Error: TypeError: binding is null
Source File: chrome://otr/content/ui.js
Line: 150

**Comment by arlolra** [comment]
Hmm, I haven't seen that in a while. Thought this was fixed in #9 

Is it reproducible? Can you elaborate on what happens at your startup? Which windows are open, accounts connect, etc.

There are only two place where `addButton` gets called,

1. When `conversation-loaded` fires. Is there any way the binding wouldn't be available there?
  https://github.com/arlolra/ctypes-otr/blob/master/chrome/content/ui.js#L328-L329

2. The other one is at startup,
  https://github.com/arlolra/ctypes-otr/blob/master/chrome/content/ui.js#L97
  but the line number for error would more likely point here in that case,
  https://github.com/arlolra/ctypes-otr/blob/master/chrome/content/ui.js#L368

**Comment by aleth** [comment]
Closer investigation shows this happens when a log is opened.

**Comment by aleth** [comment]
You could e.g. check documentElement.getAttribute("windowtype") to avoid this.

**Comment by arlolra** [comment]
Ah, I see, thanks! Why does opening a log fire `conversation-loaded`?

**Comment by aleth** [comment]
A log is displayed in a convbrowser like any other conversation. It's just that the source of the messages being added is a log and not a prpl.

**Comment by arlolra** [comment]
Thanks; I pushed a fix.

**Comment by arlolra** [comment]
Same thing with the theme selector. Should switch to a whitelist.
