### ISSUE TITLE
XMPP conversations open without user action

### ISSUE THREAD

**Issue by aleth** [arlolra/ctypes-otr#53]
I don't have precise STR, but it seems that sometimes when an XMPP contact comes online, a conversation tab is opened automatically for that contact. It contains "The current conversation is not private.", followed by "Private conversation with... started. However, their identity has not been verified.", and also a verification notification bar (but no incoming or outgoing messages).

UI detail: "conversation not private" immediately followed by "private conversation started" is something that could be tidied up.

**Comment by arlolra** [comment]
What's STR?

I'm going to guess about what's happening. The XMPP server you're using buffers messages to deliver to a contact when they come back online. Since the OTR session for the buffered messages has ended, they can't decrypt them and send you an error. We have a policy set ([OTRL_POLICY_ERROR_START_AKE](https://github.com/arlolra/ctypes-otr/blob/master/chrome/content/libotr.js#L356) that renegotiates a session when it receives an error message. It would be nice to confirm if this theory holds water.

The UI part is something we kind of discussed in the past. Because the default in Instantbird is to close a conversation when the window is closed, instead of putting it on hold, it's important to notify the user of the current trust state of the conversation when the window opens. Otherwise, again with opportunistic encryption, I could again leak an unintended plaintext message.

**Comment by aleth** [comment]
> What's STR?

Steps to reproduce

> The XMPP server you're using buffers messages to deliver to a contact when they come back online.
> Since the OTR session for the buffered messages has ended, they can't decrypt them and send you 
> an error.

That's an interesting theory. You'e saying I might have received an error message from the contact in response to offline messages I sent, and this error message was not displayed?

It should probably be ensured that we don't send OTR encrypted XMPP messages to offline contacts in that case, as offline messages are a standard XMPP feature.

I'll keep an eye out for future instances, but I thought I'd better file it before it gets forgotten.

> The UI part is something we kind of discussed in the past...

I understand this part - I'm talking about fine-tuning those system messages when they occur in sequence. In this edge case, the end result of what was on the screen was confusing.

**Comment by arlolra** [comment]
> this error message was not displayed?

It's an OTR protocol error that isn't necessarily intended to be displayed. We can test this though, if you have a minute.

> It should probably be ensured that we don't send OTR encrypted XMPP messages to offline contacts in that case, as offline messages are a standard XMPP feature.

Right, that's why clients should send the OTR disconnect message (see #1). That will end the OTR session and prevent this from happening. Do you happen to know which client your contact was using? But yes, checking that the other side is still connected before sending an encrypted message is good idea.

> I understand this part - I'm talking about fine-tuning those system messages when they occur in sequence. In this edge case, the end result of what was on the screen was confusing.

I'm definitely open to ideas here but the first one is always fired on "new-ui-conversation".

**Comment by aleth** [comment]
I've just seen this again and my guess is as follows: If you open a conversation with an offline XMPP contact and send a message, that contains whitespace which (when that contact retrieves the message) establishes a private connection. While the conversation was closed after sending the message, this will reopen it and so pop up a tab with only system messages.

Not sure about the client on the other side, probably it's Pidgin or Empathy.

**Comment by arlolra** [comment]
Aha! So we shouldn't be attaching whitespace tags if the contact isn't online.

I wonder if libotr already accounts for this and I need to fixup `is_logged_in_cb`,
https://github.com/arlolra/ctypes-otr/blob/master/chrome/content/otr.js#L468-L482

**Comment by arlolra** [comment]
> I wonder if libotr already accounts for this and I need to fixup is_logged_in_cb

Nope, that's only used to determine if we should send the disconnect msg.

Hmm, ok, this is a little tricky in that we don't want to mess with libotr internal state and inadvertently suppress opportunistic encryption for the next session. It looks like stripping the whitespace tags and setting `context->otr_offer = OFFER_NOT` should do the trick.

If I haven't said it already, thanks a lot for dogfooding and for helping to get this right.

**Comment by aleth** [comment]
You might want to observe the status of the contact and, when the contact goes offline, treat this as an otr-disconnect despite the conversation itself remaining open. (And conversely, if the contact is offline, disable "start private conv" whether opportunistic or not.)

**Comment by arlolra** [comment]
I opened [an issue](https://bugs.otr.im/issues/102) upstream for this but will probably patch it here for the time being.

**Comment by arlolra** [comment]
Pushed a workaround in 402df3226b55213b72aad7f357c0e5af4044d231.

**Comment by arlolra** [comment]
Please reopen if that doesn't work for you.

**Comment by aleth** [comment]
Looks like the workaround works!
